### ISSUE TITLE
2.32.0 release not showing on Curseforge?

### ISSUE THREAD

**Issue by AySz88** [exochron/MountJournalEnhanced#105]
Just noticed that the latest build isn't showing [on Curseforge](https://www.curseforge.com/wow/addons/mount-journal-enhanced/files/all?page=1&pageSize=20), even though it is on [Wago](https://addons.wago.io/addons/mount-journal-enhanced/versions?stability=stable). The [action](https://github.com/exochron/MountJournalEnhanced/actions/runs/7672603916/job/20913451784#step:3:375) claims success, albeit with some Node.js deprecation warnings.

(Apologies if this was intentional.)

**Comment by exochron** [comment]
Curseforge just needs sometimes a bit more time. Each release gets (manually?) approved by cf.
Although this time it took a few hours to get approved. :disappointed:
