### ISSUE TITLE
[Bug] Mount stats information bugs out if you swap tabs

### ISSUE THREAD

**Issue by zeenk** [exochron/MountJournalEnhanced#106]
~~I'd also suggest adding a "Reset window frame size" button down by the other controls if you'd like to go back to default size to match all the other tab window sizes 😄~~
Nvm, you just drag it back until you can't anymore to get the default size again so probably not needed :P

Edit: Deleted my savedvariable file just to test default settings, and no issues with default window size so it only bugs out if you have adjusted the window size

https://github.com/exochron/MountJournalEnhanced/assets/68170439/3852608a-5bf1-4ef6-9ec3-33956c55b164

**Comment by exochron** [comment]
Thank you for reporting this bug. I wouldn't have found it.  :smile:

**Comment by exochron** [comment]
just released in version 2.33.0

btw there are several reset methods for the size. (try the wrench icon or `/mje reset size`) I just wouldn't add a separate button for that onto the journal. It feels a bit unnecessary to have that always shown.

**Comment by zeenk** [comment]
> just released in version 2.33.0
> 
> btw there are several reset methods for the size. (try the wrench icon or `/mje reset size`) I just wouldn't add a separate button for that onto the journal. It feels a bit unnecessary to have that always shown.

Oh yeah I see the "Reset journal size" setting now, didn't know it existed 👍
