### ISSUE TITLE
Modifier for specific mounts

### ISSUE THREAD

**Issue by Ferdonax** [exochron/MountJournalEnhanced#115]
I want to be able to use a modifier to select a specific mount. 
In my case, I want to use ALT + Key to mount the "Traveler's Tundra Mammoth".

Would it be possible to do so without a major hassle?

**Comment by Ferdonax** [comment]
OK, so I found a solution by editing the macro like so: 

/cast [mod:alt] Traveler's Tundra Mammoth
/run C_MountJournal.SummonByID(0)

**Comment by Ferdonax** [comment]
Yeah, I should have seen this coming. The addon reverses to default with every new login/reload. 

So, I changed the code a bit:

[UI/SummonRandomButton.lua](https://github.com/exochron/MountJournalEnhanced/blob/536e9cc84c45b9827c4992bbad35b2e7fc88d465/UI/SummonRandomButton.lua#L5)

<html>
<body>



ADDON.Events:RegisterCallback("OnLogin", function()
4 | local MACRO_NAME = "MJE: Random Mount"
5 | local MACRO_BODY = "/run C_MountJournal.SummonByID(0)"
6 | local MACRO_ICON = "ability_hunter_beastcall"
7

<br class="Apple-interchange-newline">
</body>
</html>


and added 

"/run C_MountJournal.SummonByID(0)\n/cast [mod:alt] Traveler's Tundra Mammoth"

It would be great if we could have it as an option in the settings panel.

**Comment by exochron** [comment]
I'm sorry to disappoint, but I'm not going to add this as a feature.
You can simply pick another name for your macro and modify it as you like. :)
