### ISSUE TITLE
Is it possible to add a sort by family/subfamily

### ISSUE THREAD

**Issue by AmethySlime** [exochron/MountJournalEnhanced#120]
I want my cats together then the tigers within cats together.

Would this be possible, or even reasonable?

**Comment by exochron** [comment]
it is :+1:

**Comment by AmethySlime** [comment]
Damn that was quick, I am excited for the next push to Curseforge!
Thanks bud!

**Comment by exochron** [comment]
and now finally released with version 2.38.0 :)
