### ISSUE TITLE
Erro with elvui

### ISSUE THREAD

**Issue by AngelosNaoumis** [exochron/MountJournalEnhanced#125]
Getting the below error with Elvui.

6x MountJournalEnhanced/UI/SettingsDropDown.lua:188: attempt to index local 'highlight' (a nil value)
[string "@MountJournalEnhanced/UI/SettingsDropDown.lua"]:188: in function <MountJournalEnhanced/UI/SettingsDropDown.lua:162>
[string "@MountJournalEnhanced/UI/SettingsDropDown.lua"]:197: in function <MountJournalEnhanced/UI/SettingsDropDown.lua:196>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@MountJournalEnhanced/MountJournalEnhanced.lua"]:97: in function <MountJournalEnhanced/MountJournalEnhanced.lua:86>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_Collections/Blizzard_MountCollection.lua"]:650: in function <...ns/Blizzard_Collections/Blizzard_MountCollection.lua:639>
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_Collections/Blizzard_Collections.lua"]:42: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections/Blizzard_Collections.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*Blizzard_Collections.xml:7_OnClick"]:1: in function <[string "*Blizzard_Collections.xml:7_OnClick"]:1>

Locals:
template = nil
button = Button {
 menuAnchor = <table> {
 }
 menuRelativePoint = "BOTTOMLEFT"
 menuPointX = 0
 callbackTables = <table> {
 }
 intrinsic = "DropdownButton"
 menuPointY = 0
 PixelSnapDisabled = true
 Event = <table> {
 }
 Icon = Texture {
 }
 menuPoint = "TOPLEFT"
}
icon = Texture {
}
highlight = nil
(*temporary) = Button {
 menuAnchor = <table> {
 }
 menuRelativePoint = "BOTTOMLEFT"
 menuPointX = 0
 callbackTables = <table> {
 }
 intrinsic = "DropdownButton"
 menuPointY = 0
 PixelSnapDisabled = true
 Event = <table> {
 }
 Icon = Texture {
 }
 menuPoint = "TOPLEFT"
}
(*temporary) = nil
(*temporary) = true
(*temporary) = 4
(*temporary) = "attempt to index local 'highlight' (a nil value)"
withoutStyle = true

**Comment by exochron** [comment]
thank you for reporting this.
it should be fixed with version 2.39.2 :)
