### ISSUE TITLE
[Suggestion] Keyboard navigation

### ISSUE THREAD

**Issue by Meivyn** [exochron/MountJournalEnhanced#13]
Hey,

Just found this project looking on your profile.

The feature I personally want is being able to navigate through mounts with up and down keys on the keyboard, just like transmog sets. This would be amazing to quickly find a mount matching a transmog instead of clicking on each mount indefinitely and wasting a lot of time.

**Comment by exochron** [comment]
Hey Meivyn,
thats an awesome idea. I wasn't even aware that you can use the keys within the transmog tab.

**Comment by exochron** [comment]
Released with 2.1
