### ISSUE TITLE
Summon Pet with mount

### ISSUE THREAD

**Issue by Demonicka** [exochron/MountJournalEnhanced#134]
I love your addon! Please can you add the option to assign pets to mounts, as it is in the addon Mountsjournal. Right now I'm using both at the same time for that purpose, but I'd rather just use yours :)

**Comment by exochron** [comment]
Thank you! That sounds like a nice feature. :smile:

**Comment by exochron** [comment]
little sneak peak ;)
![pet assignment ui](../blob/0952eec98ab016fc5662bac10cc471cfcb63c9a8/Images/11_pet-assignment.jpg)

**Comment by exochron** [comment]
Released with version 2.44.0

Please keep in mind, that the new window still needs some improvement. Although I already have a few ideas, feedback is still appreciated. :smiley:
