### ISSUE TITLE
Cannot drag icons of unusable mounts

### ISSUE THREAD

**Issue by LudiusMaximus** [exochron/MountJournalEnhanced#33]
While I was in transit via flight master, I wanted to add some new mounts to my action bar. But to MountJournalEnhanced all mounts were unusable during the taxi flight (which makes kind of sense) and it would not let me drag and drop any mount icon. Could you make it such that the icons of unusable mounts are still draggable?

**Comment by exochron** [comment]
Hi, that actually works just fine on my client.
Just to clarify: you do mean the known but not useable mounts in red and not the untrained mounts in grey, right?
Otherwise you might have some third party addon active, which could interfere here.

**Comment by LudiusMaximus** [comment]
I'll be damned. Just tried it again and it worked. No idea what went wrong the other day. Sorry for the fuss and thanks for the reply.
