### ISSUE TITLE
Shadowlands 9.0.2 error

### ISSUE THREAD

**Issue by yoshimo** [exochron/MountJournalEnhanced#34]
Count: 1
Message: ...erface\AddOns\MountJournalEnhanced\UI\MountCount.lua line 25:
   GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: GetAchievementCriteriaInfo()
   [string "@MountJournalEnhanced\UI\MountCount.lua"]:25:
      ...erface\AddOns\MountJournalEnhanced\UI\MountCount.lua:6
   [string "@MountJournalEnhanced\UI\MountCount.lua"]:43:
      ...erface\AddOns\MountJournalEnhanced\UI\MountCount.lua:40
   [string "@MountJournalEnhanced\Settings\Handling.lua"]:10: ?()
   [string "@MountJournalEnhanced\Settings\Handling.lua"]:29: ApplySetting()
   [string "@MountJournalEnhanced\UI\MountCount.lua"]:64: callback()
   [string "@MountJournalEnhanced\MountJournalEnhanced.lua"]:106:
      ...AddOns\MountJournalEnhanced\MountJournalEnhanced.lua:104
   [string "@MountJournalEnhanced\MountJournalEnhanced.lua"]:139: LoadUI()
   [string "@MountJournalEnhanced\MountJournalEnhanced.lua"]:218:
      ...AddOns\MountJournalEnhanced\MountJournalEnhanced.lua:202

**Comment by exochron** [comment]
Just as technical note:
The hidden achievement, which tracks the personal mount count, is going to be removed with 9.0. Other achievements simply stop counting, wehen they are fullfilled. So I had to count myself again.

That is now merged into version 2.8.
