### ISSUE TITLE
Since updating none of the custom buttons work

### ISSUE THREAD

**Issue by Robytom** [exochron/MountJournalEnhanced#67]
Since updating to 2.20 (was super hyped for the rarity sort and colors thanks) none of the addon's buttons work, even tried turning all other addons off except this one and clearing the cache for it but still doesn't work. like none of the settings, sort, filter buttons etc have any effect. Default blizz elements still work like summon favourite and mount equipment. Bottom display buttons such as mountspecial, show character still work.

**Comment by exochron** [comment]
That version is alrready for patch 10.0. Please just roll back to 2.19 and wait a few days :)

**Comment by Robytom** [comment]
Ah shame, can't wait to try it out! keep up the good work :)

**Comment by exochron** [comment]
Lets keep this issue open a bit for the next one to see :)

**Comment by exochron** [comment]
Patch 10.0 is out by now. So any error happening with version 2.20 is legit. So please continue to report :)
