### ISSUE TITLE
Problems with Errors since Update

### ISSUE THREAD

**Issue by Fluke667** [exochron/MountJournalEnhanced#68]
1x ...ddOns\MountJournalEnhanced\Settings\OptionsPanel.lua:168: attempt to index global 'Settings' (a nil value)
[string "@MountJournalEnhanced\Settings\OptionsPanel.lua"]:168: in function <...ddOns\MountJournalEnhanced\Settings\OptionsPanel.lua:134>
[string "=[C]"]: ?
[string "@SharedXML\CallbackRegistry.lua"]:118: in function <SharedXML\CallbackRegistry.lua:117>
[string "=[C]"]: ?
[string "@SharedXML\CallbackRegistry.lua"]:121: in function `TriggerEvent'
[string "@MountJournalEnhanced\MountJournalEnhanced-2.20.lua"]:53: in function <MountJournalEnhanced\MountJournalEnhanced.lua:42>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:591: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1456: in function <FrameXML\UIParent.lua:1337>

Locals:
uiLabels = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
}
behaviourLabels = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
}
group = <table> {
 OnHeightSet = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:69
 type = "BlizOptionsGroup"
 AceGUIWidgetVersion = 26
 label = <unnamed> {
 }
 checks = <table> {
 }
 OnWidthSet = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:59
 LayoutFunc = <function> defined @TomTom\libs\AceGUI-3.0\AceGUI-3.0.lua:619
 OnAcquire = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:52
 base = <table> {
 }
 events = <table> {
 }
 SetName = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:79
 userdata = <table> {
 }
 children = <table> {
 }
 frame = <unnamed> {
 }
 SetTitle = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:84
 content = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 OnHeightSet = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:69
 type = "BlizOptionsGroup"
 AceGUIWidgetVersion = 26
 label = <unnamed> {
 }
 checks = <table> {
 }
 OnWidthSet = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:59
 LayoutFunc = <function> defined @TomTom\libs\AceGUI-3.0\AceGUI-3.0.lua:619
 OnAcquire = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:52
 base = <table> {
 }
 events = <table> {
 }
 SetName = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:79
 userdata = <table> {
 }
 children = <table> {
 }
 frame = <unnamed> {
 }
 SetTitle = <function> defined @TomTom\libs\AceGUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:84
 content = <unnamed> {
 }
}
(*temporary) = "default"
(*temporary) = <function> defined @MountJournalEnhanced\Settings\Handling.lua:32
(*temporary) = <table> {
 refresh = <function> defined @MountJournalEnhanced\Settings\OptionsPanel.lua:138
 okay = <function> defined @MountJournalEnhanced\Settings\OptionsPanel.lua:152
 default = <function> defined @MountJournalEnhanced\Settings\Handling.lua:32
}
(*temporary) = "attempt to index global 'Settings' (a nil value)"
ADDON = <table> {
 ResetFilterSettings = <function> defined @MountJournalEnhanced\Settings\Settings.lua:11
 Api = <table> {
 }
 DB = <table> {
 }
 ResetSettings = <function> defined @MountJournalEnhanced\Settings\Handling.lua:32
 GetSettingLabels = <function> defined @MountJournalEnhanced\Settings\Handling.lua:37
 IsPersonalMount = <function> defined @MountJournalEnhanced\PlayerConditions.lua:99
 OpenOptions = <function> defined @MountJournalEnhanced\Settings\OptionsPanel.lua:7
 settings = <table> {
 }
 Debug = <table> {
 }
 isMetric = true
 UI = <table> {
 }
 GetMountStatistics = <function> defined @MountJournalEnhanced\Tracking.lua:10
 IsUsingDefaultFilters = <function> defined @MountJournalEnhanced\Settings\Settings.lua:7
 ResetSortSettings = <function> defined @MountJournalEnhanced\Settings\Settings.lua:19
 ApplySetting = <function> defined @MountJournalEnhanced\Settings\Handling.lua:27
 FilterMounts = <function> defined @MountJournalEnhanced\Filters.lua:285
 Events = <table> {
 }
 RegisterUISetting = <function> defined @MountJournalEnhanced\Settings\Hand

**Comment by exochron** [comment]
Please see #67 :)
