### ISSUE TITLE
Receive date option

### ISSUE THREAD

**Issue by UlyanaLeyana** [exochron/MountJournalEnhanced#77]
Hi, I like the functionality of the addon, but I think it needs an option to manually add the date when player got the mount. Some receive dates are taken from achievements, but not all mounts have achievements. So it would be cool to get option to add date manually. For some mount I know exactly when I got them but addon doesn't have record for it, simply because it wasn't installed/enabled when I got the mount.
Or maybe create a FAQ for how to add dates manually for those who need it.
Thanks!

**Comment by UlyanaLeyana** [comment]
> Hi UlyanaLeyana, please check out the chat command: `/mje` There is an option that should help you. I justs don't promote it much, because it's heavily limited in its function.

Great, I tried this command, everything is working.

**Comment by exochron** [comment]
glad that helped 😃

**Comment by exochron** [comment]
For further discussions join here: https://github.com/exochron/MountJournalEnhanced/discussions/74
