### ISSUE TITLE
Mount model spinning nonstop

### ISSUE THREAD

**Issue by paradisewoods** [exochron/MountJournalEnhanced#82]
Is there a toggle for this? If not, can there be?

**Comment by exochron** [comment]
Of course there is a button for that 😉
When you hover over the model with your mouse, the control panel appears at the bottom. There is a new toggle button with the circle icon right between the zoom and rotation buttons.

Rethinking about that now, I guess it's not quite intuitive and a bit hard to find as I would have hoped. I should probably turn the auto rotation off by default.

**Comment by paradisewoods** [comment]
Thanks! I do like the feature, but I like that we can toggle it, too =)

Your addon is one of those "Why didn't they hire this person to design that part of the UI??" addons. I really appreciate the time and effort you put into it.

**Comment by exochron** [comment]
just released 2.25.1. It has the spinning turned off by default for new users.
