### ISSUE TITLE
[Bug] Mount frame position gets moved to center

### ISSUE THREAD

**Issue by zeenk** [exochron/MountJournalEnhanced#86]
Found a bug with the frame being pushed to center if you use Auctionator & this addon, if you open the shift+p menu while having the auction house open and swap between the mount & pet tab the shift+p window gets pushed to the center

It doesn't happen when you only have either Auctionator or this addon enabled, so something is happening when both addons are enabled that makes it get pushed to the center.

Edit: Only seem to happen if the mounts tab is the first tab that gets opened with shift+p while the AH window is up & Auctionator enabled after a /reload or login and then swap to any other tab, if shift+p opens any other tab first and then swap to mounts tab it doesn't happen.

## Mount tab gets opened first (bugs out when you swap to pet tab)

https://github.com/exochron/MountJournalEnhanced/assets/68170439/f777f67e-3972-44b1-a82b-71ece93406eb

## Pet tab  gets opened first (no issues)

https://github.com/exochron/MountJournalEnhanced/assets/68170439/0b23ac68-39b7-4d7a-9119-85ce9651e297

**Comment by exochron** [comment]
Thank you for reporting this bug. The good news is that I can reproduce this bug. :)
Also it has nothing to do with Auctionator. After a /reload the auction house has to be opened first before the mount journal.

**Comment by zeenk** [comment]
Oh yeah you are correct, I must have had the pet tab open first when I first tested it so it didn't bug out :P

**Comment by zeenk** [comment]
Great, can confirm it works now 😄
