### ISSUE TITLE
Feature request: port to WoTLK Classic

### ISSUE THREAD

**Issue by Barov2** [exochron/MountJournalEnhanced#88]
Same request as for Toy Box Enhanced. 😉

**Comment by Barov2** [comment]
Thank you for this first version, which allowed me to work on the translation.

The "Type" and "Faction" filters work well. With the "Expansion" filter, the name Dragonflight does not appear (unimportant to WotLK, just cosmetic).

The "Family" filter works well, except when "Hidden by the game" is checked: 11 mounts appear even when everything is unchecked.

For "Sources", 7 mounts appear when everything is unchecked, and many more when "Hidden by the game" is checked. The names of the 8th, 9th and 15th source don't appear.

**Comment by Barov2** [comment]
I tested the latest version: only the [Avatar of Flame](https://www.wowhead.com/wotlk/spell=423869/avatar-of-flame) — from the Cataclysm Classic Heroic Edition — is not classified in the Family section.

**Comment by exochron** [comment]
As you might have noticed some features are missing in the classic version. It's mostly because of technical limits of the classic client. I do hope that Blizz fixes most of it with Cata Classic.
