### ISSUE TITLE
Mount Special Button Option not working.

### ISSUE THREAD

**Issue by RAtwood90** [exochron/MountJournalEnhanced#97]
Hey Mate as you can see the Option has no Effect. 

![WoWScrnShot_120323_160608](https://github.com/exochron/MountJournalEnhanced/assets/73589071/58f13f5e-1c67-4396-9545-edb0f5faf15d)

P.S also wrote something in your ToyBoxEnhanced.

**Comment by exochron** [comment]
Your right, the mountspecial animation gets randomly cancelled.
Turns out, that happens constantly while flying/dragonriding.

**Comment by exochron** [comment]
fixed with version [2.30.2](https://github.com/exochron/MountJournalEnhanced/releases/tag/2.30.2)

**Comment by RAtwood90** [comment]
> fixed with version [2.30.2](https://github.com/exochron/MountJournalEnhanced/releases/tag/2.30.2)

![image](https://github.com/user-attachments/assets/93257f77-1196-4873-8ebd-87237aaa4085)

Issue with that is back again.
