### ISSUE TITLE
Addon compartment throws error

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [exochron/MountJournalEnhanced#99]
Not a huge issue (just found out about the addon compartment), but your addon just throws an error when clicking on the option in the addon compartment.

1x FrameXML/AddonCompartment.lua:36: attempt to call field '?' (a nil value)
[string "@FrameXML/AddonCompartment.lua"]:36: in function <FrameXML/AddonCompartment.lua:31>
[string "@FrameXML/AddonCompartment.lua"]:40: in function 'func'
[string "@SharedXML/UIDropDownMenu.lua"]:1009: in function 'UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1>

Locals:
addonCompartmentFunc = "MountJournalEnhanced_Open"
addonName = "MountJournalEnhanced"
(*temporary) = nil
(*temporary) = "MountJournalEnhanced"
(*temporary) = "LeftButton"
(*temporary) = DropDownList1Button4 {
 0 = <userdata>
 r = 0
 notCheckable = true
 g = 0
 icon = "Interface\Addons\MountJournalEnhanced\UI\icons\mje.png"
 b = 0
 Highlight = DropDownList1Button4Highlight {
 }
 invisibleButton = DropDownList1Button4InvisibleButton {
 }
 value = "Mount Journal Enhanced"
 Icon = DropDownList1Button4Icon {
 }
 func = <function> defined @FrameXML/AddonCompartment.lua:39
}
(*temporary) = "attempt to call field '?' (a nil value)"
forceinsecure = <function> defined =[C]:-1
reason = ""

**Comment by exochron** [comment]
It could actually be some internal handling within the blizz code. Luckly there is a second option to use this. I'm trying that for now.
SO should be fixed with version [2.30.2](https://github.com/exochron/MountJournalEnhanced/releases/tag/2.30.2)
